default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: booksy_development

test:
  <<: *default
  database: booksy_test

production:
  <<: *default
  database: booksy_production
